version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.9
    commands:
      - pip install --upgrade pip
      - curl -sSLo sonar-scanner.zip https://binaries.sonarsource.com/Distribution/sonar-scanner-cli/sonar-scanner-cli-4.8.0.2856.zip
      - unzip sonar-scanner.zip -d /usr/local
      - export PATH=$PATH:/usr/local/sonar-scanner-4.8.0.2856/bin

  build:
    commands:
      - echo "Starting SonarCloud analysis..."
      - sonar-scanner \
          -Dsonar.projectKey=<your-project-key> \
          -Dsonar.organization=<your-organization> \
          -Dsonar.sources=. \
          -Dsonar.host.url="https://sonarcloud.io" \
          -Dsonar.login=$SONAR_TOKEN

artifacts:
  files:
    - '**/*'
