version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.9
    commands:
      - pip install --upgrade pip --root-user-action=ignore
      - pip install -r requirements.txt pylint --root-user-action=ignore
      - curl -sSLo sonar-scanner.zip https://binaries.sonarsource.com/Distribution/sonar-scanner-cli/sonar-scanner-cli-4.8.0.2856.zip
      - unzip sonar-scanner.zip -d /usr/local
      - export PATH="$PATH:/usr/local/sonar-scanner-4.8.0.2856/bin"

  pre_build:
    commands:
      - python --version
      - pylint $CODEBUILD_SRC_DIR/*.py || true
      - pylint $CODEBUILD_SRC_DIR/stellar/**/*.py || true

  build:
    commands:
      - sonar-scanner \
          -D"sonar.projectKey=Comrade-Glitch-cloud_SocialMedia-Stellar" \
          -D"sonar.organization=comrade-glitch-cloud" \
          -D"sonar.sources=." \
          -D"sonar.host.url=https://sonarcloud.io" \
          -D"sonar.login=${sonar_token}" \
          -D"sonar.python.version=3.9" \
          -D"sonar.exclusions=**/settings.py" \
          -X

artifacts:
  files:
    - '**/*'
