# Generated by Django 4.2.16 on 2024-11-14 22:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('star_accounts_hub', '0002_alter_cadet_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cadet',
            name='bio',
        ),
        migrations.AddField(
            model_name='cadet',
            name='avatar_first_name',
            field=models.CharField(default='State your First Name', max_length=30),
        ),
        migrations.AddField(
            model_name='cadet',
            name='avatar_last_name',
            field=models.CharField(default='State your Last Name', max_length=30),
        ),
        migrations.AddField(
            model_name='cadet',
            name='stellarname',
            field=models.CharField(default='Stellar User Name', max_length=30, unique=True),
        ),
        migrations.AddField(
            model_name='cadet',
            name='valid_email',
            field=models.EmailField(default='State your Email Please', max_length=254, unique=True),
        ),
    ]
