# Generated by Django 4.2.16 on 2024-11-24 17:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('star_accounts_hub', '0003_remove_cadet_bio_cadet_avatar_first_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cadet',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='cadet', to=settings.AUTH_USER_MODEL),
        ),
    ]
