# Generated by Django 4.2.16 on 2024-11-24 22:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('star_accounts_hub', '0004_alter_cadet_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='CadetProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stellarname', models.CharField(max_length=30, unique=True)),
                ('cadet_picture', models.ImageField(blank=True, null=True, upload_to='cadet_pics/')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='cadet', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='Cadet',
        ),
    ]
