# Generated by Django 4.2.17 on 2024-12-09 03:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('star_accounts_hub', '0005_cadetprofile_delete_cadet'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cadetprofile',
            name='stellarname',
            field=models.CharField(max_length=30),
        ),
    ]
