# Generated by Django 4.2.16 on 2024-12-05 22:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stellar_posts', '0002_rename_post_stellarpost'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='stellarpost',
            unique_together=set(),
        ),
    ]
